// List of all countries with code, name, flag, and calling code
// Source: https://github.com/annexare/Countries/blob/master/data/countries.json and https://github.com/stevenrskelton/country-list/blob/master/data.json
export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', callingCode: '93' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', callingCode: '355' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', callingCode: '213' },
  { code: 'AS', name: 'American Samoa', flag: '🇦🇸', callingCode: '1' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', callingCode: '376' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', callingCode: '244' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮', callingCode: '1' },
  { code: 'AQ', name: 'Antarctica', flag: '🇦🇶', callingCode: '672' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', callingCode: '1' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', callingCode: '54' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', callingCode: '374' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼', callingCode: '297' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', callingCode: '61' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', callingCode: '43' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', callingCode: '994' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', callingCode: '1' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', callingCode: '973' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', callingCode: '880' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', callingCode: '1' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', callingCode: '375' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', callingCode: '32' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', callingCode: '501' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', callingCode: '229' },
  { code: 'BM', name: 'Bermuda', flag: '🇧🇲', callingCode: '1' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', callingCode: '975' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', callingCode: '591' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', callingCode: '387' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', callingCode: '267' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', callingCode: '55' },
  { code: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴', callingCode: '246' },
  { code: 'VG', name: 'British Virgin Islands', flag: '🇻🇬', callingCode: '1' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', callingCode: '673' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', callingCode: '359' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', callingCode: '226' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', callingCode: '257' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', callingCode: '855' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', callingCode: '237' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', callingCode: '1' },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', callingCode: '238' },
  { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾', callingCode: '1' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', callingCode: '236' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', callingCode: '235' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', callingCode: '56' },
  { code: 'CN', name: 'China', flag: '🇨🇳', callingCode: '86' },
  { code: 'CX', name: 'Christmas Island', flag: '🇨🇽', callingCode: '61' },
  { code: 'CC', name: 'Cocos Islands', flag: '🇨🇨', callingCode: '61' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', callingCode: '57' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', callingCode: '269' },
  { code: 'CK', name: 'Cook Islands', flag: '🇨🇰', callingCode: '682' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', callingCode: '506' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', callingCode: '385' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', callingCode: '53' },
  { code: 'CW', name: 'Curacao', flag: '🇨🇼', callingCode: '599' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', callingCode: '357' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', callingCode: '420' },
  { code: 'CD', name: 'Democratic Republic of the Congo', flag: '🇨🇩', callingCode: '243' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', callingCode: '45' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', callingCode: '253' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', callingCode: '1' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', callingCode: '1' },
  { code: 'TL', name: 'East Timor', flag: '🇹🇱', callingCode: '670' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', callingCode: '593' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', callingCode: '20' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', callingCode: '503' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', callingCode: '240' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', callingCode: '291' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', callingCode: '372' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', callingCode: '251' },
  { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰', callingCode: '500' },
  { code: 'FO', name: 'Faroe Islands', flag: '🇫🇴', callingCode: '298' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', callingCode: '679' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', callingCode: '358' },
  { code: 'FR', name: 'France', flag: '🇫🇷', callingCode: '33' },
  { code: 'GF', name: 'French Guiana', flag: '🇬🇫', callingCode: '594' },
  { code: 'PF', name: 'French Polynesia', flag: '🇵🇫', callingCode: '689' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', callingCode: '241' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', callingCode: '220' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', callingCode: '995' },
  // ... (add all other countries, up to 200+ entries) ...
]; 